### ISSUE TITLE
store SEBAL execution metadata

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/sebal-engine#10]
We need to support the replication of SEBAL execution. To do so, we need to know both the input data and the code that was used to execute. These data should be kept in fetched database (in scheduler as well)

**Comment by EsdrasVP** [comment]
Commiting implementation of the metadata storage in DB 451dff4fca7e75af4d268faf1e028ac1ec5976cf

**Comment by thiagomanel** [comment]
I think we should move sebal R code to the repository. Not sure if we should move it to sebal-scheduler or to create a new project to it.

**Comment by fubica** [comment]
We should create a new project, called SEBAL.

**Comment by thiagomanel** [comment]
@EsdrasVP, follow fubica's advice. Remove old java code from https://github.com/fogbow/SEBAL and add the R script code. Also, a remind: we need to split sebal-scheduler code in the near future (then the "scheduler" piece should be moved to a new project) see #19

**Comment by thiagomanel** [comment]
@EsdrasVP this is related to SEBAL reorganization (see https://github.com/fogbow/SEBAL/issues/31)

**Comment by EsdrasVP** [comment]
Closing old issue.

**Comment by EsdrasVP** [comment]
Closing old issue.
