### ISSUE TITLE
Allow to purge scheduler database

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/sebal-engine#14]
we should allow the SEBAL admin to purge old (e.g fetched) entries. To help him, we might add a timestamp column to indicate state changes, for example, the day a imagem was fetched. In this way, the admin user should be able to remove all fetched before some specific day.

Maybe, it is also useful to remove images by an ID key

**Comment by EsdrasVP** [comment]
The code must, later, deal with purge iterations, considering whenever the user want to remove an image from DB that doesn't is in FETCHED state, for instance

**Comment by EsdrasVP** [comment]
One way to do the purge might be using DBBootstrapMain, passing as argument some specific day, making Bootstrap mark all images before this day as "TO_PURGE" or just "PURGE". This way, a Crawler can verify in DB which image has this state and remove it.

**Comment by EsdrasVP** [comment]
Consider cases where image states were set "TO_PURGE" or "PURGED" when another entity (like worker node or fetcher, for instance) is manipulating these files somehow. In this scenario, the code will have to deal with this kind of problem everytime it happens.

**Comment by EsdrasVP** [comment]
For the above case, there might be two solutions:

- Add a new entry to the DB, which will state if that image is being used by other entity or if it's free. This way, the modification to purge state will only be made if the image is free;
- If an entity is using the image and user set via Bootstrap to purge that image, the entity immediatly stop and search for another image not purged. For this case, the entity should aways check whether the image state was changed or not.

**Comment by thiagomanel** [comment]
Hi @EsdrasVP,
I think both solutions are not ok. I would try something simpler before. For example, any entity (worker, scheduler or crawler), after doing some work (e.g executing or downloading image) checks whether the image was "purged" or is still available. If available, it proceeds with the "normal" execution flow, if not, just "clean" the state (e.g remove the downloaded data, in case it is a crawler).

Of course, I'm not aware of all implementation details but I guess it is the way to go. Tell me if you see any problem with this approach.

**Comment by thiagomanel** [comment]
... and to avoid concurrency problems with the update of image state, you may think about adding another column which has "purged" and "available" states.

**Comment by fubica** [comment]
To avoid concurrency problems updates to the DB need to be encapsulated into transactions. This applies to the issue being discussed, but also to avoid other problems where concurrent access is possible (eg. two crawlers trying to download the same image; the transaction should be such that testing whether an image is in the state "ToBeDownloaded" and changing the state of a "ToBeDownloaded" image to "Downloading are executed atomically in the same transaction.

Regarding the housekeeping required when an image is purged, perhaps the best is really to keep the current state machine (that does not has a purged state) and add a flag indicating whether the image has been purged or not. Any component that acts upon an image should first test whether the image has been purged or not.

**Comment by EsdrasVP** [comment]
Closing old issue.
