### ISSUE TITLE
[execution-test] scheduler only gets one NFS server

### ISSUE THREAD

**Issue by EsdrasVP** [fogbow/sebal-engine#23]
In the current implementation of the project, SebalMain only receives one address and port related to an NFS server. In the future, this must change to allow Scheduler redirect more than one NFS servers (Crawlers) to it's worker nodes.

**Comment by thiagomanel** [comment]
Maybe it is already ok. Since the sites [crawler + workers nodes] are not in the same network, we can use the same address:port.
