### ISSUE TITLE
evaluate the impact of the VM flavour in the performance

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/sebal-engine#28]
We are using a balanced flavour with a 300GB storage. In cloud3 terms it means storing data in Ceph DFS. Sebal execution is also data intensive (we write circa 50GB); I'm afraid doing this in a DFS will hurt our performance.

Maybe, we should pick a cloud3 performance flavour and try to find a way to have the storage closer to the compute.

**Comment by EsdrasVP** [comment]
We tested and there is no impact.
