### ISSUE TITLE
register workflow execution erros in the catalog DB

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/sebal-engine#30]
Errors on workflow execution, such as an errors in FMask step, should be registered in the catalog DB. We might to this by adding a new state (say **ERROR**) and a new column **strerror** to identify the error root cause.

**Comment by thiagomanel** [comment]
Note that, this is to be use to errors that we cannot recover during workflow execution.

**Comment by EsdrasVP** [comment]
Closing old issue.
