### ISSUE TITLE
[enhancement] let available sebal-engine jar to ease application relaunch

### ISSUE THREAD

**Issue by EsdrasVP** [fogbow/sebal-engine#40]
Currently, all infrastructure must be relaunched to use another sebal-engine version. In further changes, is necessary to let available the jar for the project's most updated version.

**Comment by thiagomanel** [comment]
not sure about **all**

**Comment by EsdrasVP** [comment]
Correction: not all infrastructure, but to the component that was afected by the update.

**Comment by EsdrasVP** [comment]
This is not valid anymore. Currently, only configuration file (sebal.conf), jar dependencies in target/lib and component version must be changed in case of code update.

One thing that might let this even more easy is to pre-install maven in each main component machine, so jar files can be generated in it.
