### ISSUE TITLE
limit instance orders from SEBAL to fogbow manager

### ISSUE THREAD

**Issue by EsdrasVP** [fogbow/sebal-engine#41]
Currently, SEBAL is ordering more resources for fogbow manager than it is able to use, generating a lot of open orders that will be deleted by fogbow manager due to timeout (because SEBAL execution lasts about eight ours).

**Comment by thiagomanel** [comment]
I think the case is more akin to have an optional **max_orders** parameter (it should be useful in a  n earlier test phase) to avoid wasting resources. Btw, note that we can achieve the same by creating a smaller number of tasks.

**Comment by EsdrasVP** [comment]
Already done in issue #78
