### ISSUE TITLE
Remove garbage from swift when necessary

### ISSUE THREAD

**Issue by EsdrasVP** [fogbow/sebal-engine#52]
When Fetcher fails to upload all files to swift, some garbage is left in containter. To fix this, Fetcher must  delete uploaded images when transfer stops in the middle of the process.

**Comment by thiagomanel** [comment]
I did not see the code yet but, in many cases, it is useful to adding a garbage check when the component is started (note that, some failures crash the component, thus we are not able to do the garbage collection)

**Comment by EsdrasVP** [comment]
0ac798b95b541d1351c1e79d97aa7e143f6d1c2e

**Comment by EsdrasVP** [comment]
The current delete method uses a process builder with a call to openstack CLI. But current implementation in Fetcher of JOSS swift client might have some useful code for this purpose.
