### ISSUE TITLE
allow the sebal user to pinpoint the worker code to be executed by SEBAL

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/sebal-engine#55]
the way to go is to pass the github url (this url must have the specific commit point of github history)

**Comment by EsdrasVP** [comment]
Also, image processing in Worker depends of additional R packages, such as:

- sp
- raster
- rgeos
- rgdal
- maptools
- ncdf4

**Comment by EsdrasVP** [comment]
Specify only git repository url instead of version (commit). This is to allow to use other repositories other than ours. 

If url is not passed, then use a default repository in sebal.conf.

**Comment by thiagomanel** [comment]
Remember to use tags instead of version (commit)

**Comment by EsdrasVP** [comment]
9747427d40b828deb683c546cac1bbbd27aa33ff

**Comment by EsdrasVP** [comment]
In case of missing R packages, user holds the responsability of getting correct dependencies for execution.

In our case, consider to use 
- "package_name" %in% rownames(installed.packages())

Which return TRUE or FALSE, informing if a given package is installed or not.

**Comment by EsdrasVP** [comment]
aea89bd5bc61f19ffc4ac53701117454d8ce6e29

**Comment by EsdrasVP** [comment]
48bb4950546dcffbf0d573119c7a97a20353c8be

**Comment by EsdrasVP** [comment]
Is important to know that the modification above allows the use of two scripts in task, but Execution Monitor must be analyzed to see if it recognize the process output from both scripts.

**Comment by EsdrasVP** [comment]
Execution Monitor already verify each process output in task.

It only marks task as completed if all commands have been executed correctly.

**Comment by EsdrasVP** [comment]
09fe3f9aa889f6c08c08afe9d2debfdc22113a89

**Comment by EsdrasVP** [comment]
Done.
