### ISSUE TITLE
remove unnecessary logging from the crawler

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/sebal-engine#58]
It seems we have many unnecessary log lines lines with the same content). Crawler produced more than 20GB of data (it is too much, since we had a very low activity in the first test).

Also, the log was not properly rotated (I was expecting to see some *.gz files after the issue #39)

**Comment by EsdrasVP** [comment]
This occurs because Crawler keeps searching images in database, even when there is no more data to be downloaded. It has the disk space, but does not have new images.

A way to deal with this is putting Crawler in sleep mode when it detects that database has no images to download.
