### ISSUE TITLE
notify SEBAL-engine users about task completion

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/sebal-engine#66]
the user should allowed to on/off the notification system (in the web interface).
SEBAL-engine should send notification via email.
A notification should be sent after fetching an image.

we need an periodic service of pending notifications communicating with the Task catalog.
we need a submission id (should be generated by the SEBAL-engine).

the notification email subject should have the submission ID and the image name
the notification email should have the parameters the user submitted.

**Comment by EsdrasVP** [comment]
5a2a9396a94eae94157ac362abf423762de556e7

**Comment by EsdrasVP** [comment]
Maybe the jobId will not be used in this implementation.
